runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /css
  static_dir: css
- url: /image
  static_dir: image
- url: /.*
  script: main.app
